# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/base:current

    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: "Say hello"
          command: |
              echo "Hello, World!"
              COMMIT_MESSAGE=$(git log -1 --pretty=%B)
              echo "Commit Message: $COMMIT_MESSAGE"
          environment:
              GIT_COMMIT_DESC: $(git log --format=oneline -n 1 $CIRCLE_SHA1)
      - run:
          name: "Setup custom environment variables"
          command: echo 'export MY_ENV_VAR="FOO"' >> "$BASH_ENV"
      - run: # print the name of the branch we're on
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}
      # Run another step, the same as above; note that you can
      # invoke environment variable without curly braces.
      - run:
          name: "What branch am I on now?"
          command: echo $CIRCLE_BRANCH
      - run:
          name: "What was my custom environment variable?"
          command: echo ${MY_ENV_VAR}
      - run:
          name: "Print an env var stored in the Project"
          command: echo ${PROJECT_ENV_VAR}
      - run:
          name: "Print an env var stored in a Context"
          command: echo ${CONTEXT_ENV_VAR}

  create_release:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      # - run:
      #     name: Install GitHub CLI
      #     command: |
      #       curl -sL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo apt-key add -
      #       sudo apt-add-repository https://cli.github.com/packages
      #       sudo apt-get update
      #       sudo apt-get install gh
      - run:
          name: Create Git Release
          command: |
            echo "Creating a release"
            # Define variables
            REPO="vuong8/terraform-module-template"  # Replace with your GitHub repository
            TAG="v$(date +%Y%m%d%H%M%S)"
            COMMIT_MESSAGE=$(git log -1 --pretty=%B)
            RELEASE_NAME="Release $(date +%Y-%m-%d)"
            RELEASE_BODY="Release notes for $(date +%Y-%m-%d) \n $COMMIT_MESSAGE"

            # Create the release via GitHub API
            curl -X POST \
              -H "Authorization: token $GH_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              -d @- https://api.github.com/repos/$REPO/releases \<<EOF
            {
              "tag_name": "$TAG",
              "name": "$RELEASE_NAME",
              "body": "$RELEASE_BODY",
              "draft": false,
              "prerelease": false
            }
            EOF
          environment:
            GH_TOKEN: $GH_TOKEN
      - run:
          name: Verify Release
          command: |
            curl -H "Authorization: token $GH_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/your-username/your-repo/releases/tags/$TAG
      # - run:
      #     name: Create Git Release
      #     command: |
      #       echo "Creating a release"
      #       gh auth login --with-token
      #       COMMIT_MESSAGE=$(git log -1 --pretty=%B)
      #       gh release create v$(date +%Y%m%d%H%M%S) --title "[Release $(date +%Y-%m-%d)] $COMMIT_MESSAGE" --notes "Release notes for $(date +%Y-%m-%d)"
      #     environment:
      #       GH_TOKEN: $GH_TOKEN
      # - run:
      #     name: Verify Release
      # #     command: |
      #       gh release view v$(date +%Y%m%d%H%M%S)

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - say-hello:
          filters:
              branches:
                  only:
                    - main
                    - release
      - create_release:
          filters:
              branches:
                  only:
                    - release